### ISSUE TITLE
invalid character 'u' looking for beginning of value

### ISSUE THREAD

**Issue by bd21** [strangelove-ventures/noble-cctp-relayer#10]
> │ 7:36PM INF New stream msg from 0 with tx hash 0x9904b00e455ce4fd7b99a9d6cd6677282c5581eef1ed5d86037fb448c9bc2848                                               │
> │ 7:36PM INF Filtered tx 0x9904b00e455ce4fd7b99a9d6cd6677282c5581eef1ed5d86037fb448c9bc2848 because relaying from 0 to 5 is not enabled                          │
> │ invalid character 'u' looking for beginning of value                                                                                                           │
> │ 7:47PM DBG non 200 response received for Noble block 3601620                                                                                                   │
> │ 7:55PM INF New stream msg from 0 with tx hash 0x37bb6c1e3adea76b34713fffa2dbb2b7efc7d1e8b9d8edfff73e09464f47cfd8                                               │
> │ 7:55PM INF Filtered tx 0x37bb6c1e3adea76b34713fffa2dbb2b7efc7d1e8b9d8edfff73e09464f47cfd8 because relaying from 0 to 1 is not enabled                          │
> │ 9:16PM INF New stream msg from 0 with tx hash 0x6ab2a090b04e8ffff230cc6bb88aef52e03bbbfc5f110230fd62529b67889eff                                               │
> │ 9:16PM INF Filtered tx 0x6ab2a090b04e8ffff230cc6bb88aef52e03bbbfc5f110230fd62529b67889eff because relaying from 0 to 1 is not enabled                          │
> │ 9:18PM INF New stream msg from 0 with tx hash 0x76c8215667bb236d029e2ff88156384a31b4e5b0c6cb24eabeeb3b5793137306                                               │
> │ 9:18PM INF Filtered tx 0x76c8215667bb236d029e2ff88156384a31b4e5b0c6cb24eabeeb3b5793137306 because relaying from 0 to 1 is not enabled                          │
> │ 9:20PM INF New stream msg from 0 with tx hash 0xe6b61c0b705dbac679185f7259f4676648c6fcd9727da5254ddb4a52be02f43a                                               │
> │ 9:20PM INF Filtered tx 0xe6b61c0b705dbac679185f7259f4676648c6fcd9727da5254ddb4a52be02f43a because relaying from 0 to 1 is not enabled                          │
> │ 9:24PM INF New stream msg from 0 with tx hash 0xf85f36ff6219e92558b6a53b235b6069c453650841bc78a9254e9bc302978a5f                                               │
> │ 9:24PM INF Filtered tx 0xf85f36ff6219e92558b6a53b235b6069c453650841bc78a9254e9bc302978a5f because relaying from 0 to 1 is not enabled                          │
> │ 9:25PM INF New stream msg from 0 with tx hash 0xe0858180c9551f5333e45de5dc69298e9104bc2021a184efaadf964760bbcc28                                               │
> │ 9:25PM INF Filtered tx 0xe0858180c9551f5333e45de5dc69298e9104bc2021a184efaadf964760bbcc28 because relaying from 0 to 1 is not enabled                          │
> │ invalid character 'u' looking for beginning of value

Steps to fix
- reproduce
- determine root cause
- push fix + test

**Comment by jtieri** [comment]
Still haven't been able to reproduce this one even when adjusting the `testnet.yaml` file to have a `start-block` that references the block height from txID: `0x9904b00e455ce4fd7b99a9d6cd6677282c5581eef1ed5d86037fb448c9bc2848`, which appears to be the problematic tx if I am reading the included logs above correctly.

My naive guess is that there is an attempt to unmarshal the results of some API call where we are expecting a JSON encoded response but the response we are attempting to unmarshal is not actually valid JSON.

**Comment by jonathanpberger** [comment]
@jtieri added better error handling in #18 

Closing ticket.
