### ISSUE TITLE
Add method to validate config file

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/noble-cctp-relayer#51]
See discussion: https://github.com/strangelove-ventures/noble-cctp-relayer/pull/49#discussion_r1508088961

**Comment by joelsmith-2019** [comment]
This feature was implemented in v0.1.4, but it does not extensively validate all of the config options. It only tests the Circle API config settings. I'll work on creating a new PR which more extensively detects misconfigurations throughout the entire file.

https://github.com/strangelove-ventures/noble-cctp-relayer/blob/61ff2d1cbe5dc5d8a33914477f017d7c9d34a452/cmd/appstate.go#L77-L87
